version: '3.8'

services:
  db:
    image: postgres:15-alpine
    env_file: ./online-judge-backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  backend:
    build: ./online-judge-backend
    ports:
      - "8000:8000"
    volumes:
      - ./online-judge-backend:/src
    env_file: ./online-judge-backend/.env
    depends_on:
      - db
      - redis

  worker:
    build: ./online-judge-backend
    command: celery -A app.core.celery_app worker --loglevel=info
    volumes:
      - ./online-judge-backend:/src
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: ./online-judge-backend/.env
    depends_on:
      - db
      - redis

  frontend:
    build: ./online-judge-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
